import { Footer } from '@/components/footer';
import { Logo } from "@/components/logo";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const promptFont = Prompt({ 
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={promptFont.className}>
        <div className="bg-[#0A0A0A]/50 backdrop-blur-[100px] flex justify-center">
          <div className="flex py-6 items-center max-w-[1280px] w-full">
            <Link href={"/"}>
              <Logo />
            </Link>
            <nav
              className={cn("flex items-center space-x-4 lg:space-x-6  ml-8")}
            >
              {/* <Link
                href={"/"}
                className="text-sm font-medium transition-colors hover:text-primary"
              >
                Home
              </Link> */}
            </nav>
            <div className="ml-auto flex items-center space-x-4">
              <Button size={"custom"} className='uppercase'>Connect Wallet</Button>
            </div>
          </div>
        </div>
        <div className="bg-background">
          <div className="">
            {/* <Sidebar className="hidden lg:block" /> */}
            <div className="">
              <div className="h-full">{children}</div>
            </div>
          </div>
        </div>

        <Footer/>
      </body>
    </html>
  );
}
