import { Footer } from '@/components/footer';
import { Nav } from '@/components/nav';
import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import Providers from '@/providers/provider';

const promptFont = Prompt({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
}
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={promptFont.className}>
        <Providers>
          <Nav />
          <div className="bg-background">
            <div className="">
              {/* <Sidebar className="hidden lg:block" /> */}
              <div className="">
                <div className="h-full">{children}</div>
              </div>
            </div>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
